FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# ENV TZ=Asia/Seoul
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV TZ=Asia/Seoul

RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]