FROM node:20-alpine

WORKDIR /app


ENV TZ=Asia/Seoul

RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone 
    
COPY package*.json yarn.lock ./
RUN yarn install



COPY . .

EXPOSE 20000

CMD ["yarn", "start:dev"]