FROM node:20-alpine

WORKDIR /app

COPY package*.json yarn.lock ./
RUN yarn install

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . .

EXPOSE 20000

CMD ["yarn", "start:dev"]